[package]
name = "more-or-less"
version = "0.1.0"
authors = ["Jérôme Bourgeois <bourgeoisjerome.pro@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.25.3"
rand = "0.8.3"
colored = "2.0.0"